global:
  # Scrape frequency for all jobs
  scrape_interval: 15s 

scrape_configs:
  # Job 1: Prometheus Self-Monitoring 
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090'] 
      
  # Job 2: Host Infrastructure Monitoring (EC2) - FINAL FIX
  - job_name: 'node_exporter'
    static_configs:
      # Uses the explicit hostname from the docker-compose extra_hosts section
      - targets: ['host.docker.internal:9100'] 
      
  # Job 3: Application Metrics 
  - job_name: 'backend_application'
    static_configs:
      - targets: ['backend:8000']